import { ColleagueProfile, TaskPulseItem, ColleaguePulseFeedItem, Project } from "./types";

export const mockColleagues: ColleagueProfile[] = [
  {
    id: "user-sarah",
    name: "Sarah Chen",
    role: "manager",
    department: "Engineering",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop&crop=face",
    activeTaskCount: 2,
    maxBandwidth: 5,
    isOnline: true,
  },
  {
    id: "user-marcus",
    name: "Marcus Vance",
    role: "member",
    department: "Engineering",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop&crop=face",
    activeTaskCount: 2,
    maxBandwidth: 5,
    isOnline: true,
  },
  {
    id: "user-elena",
    name: "Elena Rostova",
    role: "member",
    department: "Marketing",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&crop=face",
    activeTaskCount: 3,
    maxBandwidth: 5,
    isOnline: true,
  },
  {
    id: "user-david",
    name: "David Kim",
    role: "member",
    department: "Design",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop&crop=face",
    activeTaskCount: 1,
    maxBandwidth: 5,
    isOnline: false,
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj-web",
    name: "Website Building",
    code: "WEB",
    department: "Engineering",
    description: "Backend development, frontend design, and interactive features",
    progressPercentage: 62,
    targetDate: "Oct 15",
  },
  {
    id: "proj-mktg",
    name: "Digital Marketing",
    code: "MKTG",
    department: "Marketing",
    description: "Facebook ads, ads optimization, planning, and creative ideas",
    progressPercentage: 54,
    targetDate: "Nov 01",
  },
];

export const mockTasks: TaskPulseItem[] = [
  // Website Building - Backend Tasks
  {
    id: "task-web-1",
    projectId: "proj-web",
    projectName: "Website Building",
    title: "Backend: Database Schema & Auth APIs",
    department: "Engineering",
    projectBadge: "WEB-BACKEND",
    status: "in_review",
    progressPercentage: 80,
    priority: "high",
    assignee: mockColleagues[1], // Marcus
    subtasks: [
      { id: "sub-1", title: "Design PostgreSQL relational schema", completed: true },
      { id: "sub-2", title: "Setup JWT & Session validation middleware", completed: true },
      { id: "sub-3", title: "Write automated migration scripts", completed: true },
      { id: "sub-4", title: "Security audit on user role claims", completed: false },
    ],
    createdAt: "2026-09-15T08:00:00Z",
    updatedAt: "2026-09-17T09:00:00Z",
  },
  {
    id: "task-web-2",
    projectId: "proj-web",
    projectName: "Website Building",
    title: "Backend: Payment Webhook Ingestion",
    department: "Engineering",
    projectBadge: "WEB-BACKEND",
    status: "backlog",
    progressPercentage: 0,
    priority: "medium",
    assignee: mockColleagues[1], // Marcus
    subtasks: [
      { id: "sub-5", title: "Implement Stripe webhook signature verification", completed: false },
      { id: "sub-6", title: "Handle idempotency keys for duplicate events", completed: false },
    ],
    createdAt: "2026-09-16T10:00:00Z",
    updatedAt: "2026-09-16T10:00:00Z",
  },
  // Website Building - Frontend Tasks
  {
    id: "task-web-3",
    projectId: "proj-web",
    projectName: "Website Building",
    title: "Frontend: Design System & Component Library",
    department: "Design",
    projectBadge: "WEB-UI",
    status: "completed",
    progressPercentage: 100,
    priority: "high",
    assignee: mockColleagues[3], // David
    subtasks: [
      { id: "sub-7", title: "Figma design token export", completed: true },
      { id: "sub-8", title: "Responsive Navigation Bar", completed: true },
      { id: "sub-9", title: "Accessible dark mode palette", completed: true },
    ],
    createdAt: "2026-09-14T11:00:00Z",
    updatedAt: "2026-09-17T07:00:00Z",
  },
  {
    id: "task-web-4",
    projectId: "proj-web",
    projectName: "Website Building",
    title: "Frontend: Interactive Landing Page & Features",
    department: "Engineering",
    projectBadge: "WEB-UI",
    status: "in_progress",
    progressPercentage: 66,
    priority: "critical",
    assignee: mockColleagues[0], // Sarah
    subtasks: [
      { id: "sub-10", title: "Hero animation and CTA conversion flow", completed: true },
      { id: "sub-11", title: "Interactive feature pricing calculator", completed: true },
      { id: "sub-12", title: "SEO meta tags & OpenGraph card preview", completed: false },
    ],
    createdAt: "2026-09-16T09:00:00Z",
    updatedAt: "2026-09-17T08:30:00Z",
  },

  // Digital Marketing Tasks (Facebook ads, Ads optimization, Planning, Ideas)
  {
    id: "task-mktg-1",
    projectId: "proj-mktg",
    projectName: "Digital Marketing",
    title: "Facebook Ads: Campaign Setup & Targeting",
    department: "Marketing",
    projectBadge: "MKTG-ADS",
    status: "in_progress",
    progressPercentage: 66,
    priority: "high",
    assignee: mockColleagues[2], // Elena
    subtasks: [
      { id: "sub-13", title: "Install Meta Conversions API (CAPI)", completed: true },
      { id: "sub-14", title: "Upload video & carousel creative assets", completed: true },
      { id: "sub-15", title: "Configure A/B lookalike audience split", completed: false },
    ],
    createdAt: "2026-09-16T12:00:00Z",
    updatedAt: "2026-09-17T09:10:00Z",
  },
  {
    id: "task-mktg-2",
    projectId: "proj-mktg",
    projectName: "Digital Marketing",
    title: "Ads Optimization: Budget & Performance Review",
    department: "Marketing",
    projectBadge: "MKTG-OPT",
    status: "backlog",
    progressPercentage: 0,
    priority: "medium",
    assignee: mockColleagues[2], // Elena
    subtasks: [
      { id: "sub-16", title: "Review CPA and ROAS thresholds", completed: false },
      { id: "sub-17", title: "Shift spend to winning ad sets", completed: false },
    ],
    createdAt: "2026-09-17T07:00:00Z",
    updatedAt: "2026-09-17T07:00:00Z",
  },
  {
    id: "task-mktg-3",
    projectId: "proj-mktg",
    projectName: "Digital Marketing",
    title: "Planning: Campaign Timeline & Content Schedule",
    department: "Marketing",
    projectBadge: "MKTG-PLAN",
    status: "backlog",
    progressPercentage: 0,
    priority: "medium",
    assignee: mockColleagues[2], // Elena
    subtasks: [
      { id: "sub-18", title: "Finalize weekly content & posting calendar", completed: false },
      { id: "sub-19", title: "Allocate budget by channel and target milestone", completed: false },
    ],
    createdAt: "2026-09-17T07:30:00Z",
    updatedAt: "2026-09-17T07:30:00Z",
  },
  {
    id: "task-mktg-4",
    projectId: "proj-mktg",
    projectName: "Digital Marketing",
    title: "Ideas: Creative Hooks & Copywriting Concepts",
    department: "Design",
    projectBadge: "MKTG-IDEAS",
    status: "in_progress",
    progressPercentage: 50,
    priority: "high",
    assignee: mockColleagues[3], // David
    subtasks: [
      { id: "sub-20", title: "Brainstorm 10 high-converting ad hooks", completed: true },
      { id: "sub-21", title: "Design 5 static banner visual concepts", completed: false },
    ],
    createdAt: "2026-09-17T08:00:00Z",
    updatedAt: "2026-09-17T09:15:00Z",
  },
];

export const mockPulseFeed: ColleaguePulseFeedItem[] = [
  {
    userId: "user-sarah",
    displayName: "Sarah Chen",
    avatarUrl: mockColleagues[0].avatarUrl,
    department: "Engineering",
    projectName: "Website Building",
    currentTaskTitle: "Frontend: Interactive Landing Page & Features",
    projectBadge: "WEB-UI",
    progressPercentage: 66,
    activeTaskCount: 2,
    isBlocked: false,
    lastHeartbeat: "Just now",
  },
  {
    userId: "user-elena",
    displayName: "Elena Rostova",
    avatarUrl: mockColleagues[2].avatarUrl,
    department: "Marketing",
    projectName: "Digital Marketing",
    currentTaskTitle: "Facebook Ads: Campaign Setup & Targeting",
    projectBadge: "MKTG-ADS",
    progressPercentage: 66,
    activeTaskCount: 3,
    isBlocked: false,
    lastHeartbeat: "3m ago",
  },
  {
    userId: "user-marcus",
    displayName: "Marcus Vance",
    avatarUrl: mockColleagues[1].avatarUrl,
    department: "Engineering",
    projectName: "Website Building",
    currentTaskTitle: "Backend: Database Schema & Auth APIs",
    projectBadge: "WEB-BACKEND",
    progressPercentage: 80,
    activeTaskCount: 2,
    isBlocked: false,
    lastHeartbeat: "5m ago",
  },
  {
    userId: "user-david",
    displayName: "David Kim",
    avatarUrl: mockColleagues[3].avatarUrl,
    department: "Design",
    projectName: "Digital Marketing",
    currentTaskTitle: "Ideas: Creative Hooks & Copywriting Concepts",
    projectBadge: "MKTG-IDEAS",
    progressPercentage: 50,
    activeTaskCount: 1,
    isBlocked: false,
    lastHeartbeat: "10m ago",
  },
];
