# TaskPulse - Firebase Google Login Configuration Wizard

Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "        TaskPulse: Firebase & Google OAuth Setup          " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "To enable official Google OAuth login (accounts.google.com):" -ForegroundColor Yellow
Write-Host "1. Open https://console.firebase.google.com and click 'Add project' (or select an existing project)."
Write-Host "2. Go to 'Build' -> 'Authentication' -> 'Sign-in method' -> enable 'Google'."
Write-Host "3. Go to 'Project Settings' -> 'General' -> under 'Your apps', click the Web '</>' icon."
Write-Host "4. Copy the firebaseConfig snippet."
Write-Host ""

$inputChoice = Read-Host "Do you want to paste the full 'firebaseConfig = {...}' snippet? (Y/n)"

$apiKey = ""
$projectId = ""
$authDomain = ""
$storageBucket = ""
$messagingSenderId = ""
$appId = ""

if ($inputChoice -ne "n" -and $inputChoice -ne "N") {
    Write-Host "`nPaste your firebaseConfig code snippet below (press Enter, then type 'DONE' on a new line and press Enter):" -ForegroundColor Cyan
    $lines = @()
    while ($true) {
        $line = Read-Host
        if ($line.Trim() -eq "DONE") { break }
        $lines += $line
    }
    $rawText = $lines -join "`n"

    # Extract properties using regex
    function Extract-Field($fieldName, $text) {
        if ($text -match "['""]?$fieldName['""]?\s*:\s*['""]([^'""]+)['""]") {
            return $matches[1]
        }
        return ""
    }

    $apiKey = Extract-Field "apiKey" $rawText
    $projectId = Extract-Field "projectId" $rawText
    $authDomain = Extract-Field "authDomain" $rawText
    $storageBucket = Extract-Field "storageBucket" $rawText
    $messagingSenderId = Extract-Field "messagingSenderId" $rawText
    $appId = Extract-Field "appId" $rawText
}

if ([string]::IsNullOrWhiteSpace($apiKey)) {
    Write-Host "`nEntering details manually:" -ForegroundColor Yellow
    $apiKey = Read-Host "Firebase apiKey (e.g. AIzaSy...)"
    $projectId = Read-Host "Firebase projectId (e.g. taskpulse-app)"
    $authDomain = Read-Host "Firebase authDomain [Default: $projectId.firebaseapp.com]"
    if ([string]::IsNullOrWhiteSpace($authDomain)) { $authDomain = "$projectId.firebaseapp.com" }
    $storageBucket = Read-Host "Firebase storageBucket [Default: $projectId.appspot.com]"
    if ([string]::IsNullOrWhiteSpace($storageBucket)) { $storageBucket = "$projectId.appspot.com" }
    $appId = Read-Host "Firebase appId (optional)"
}

if ([string]::IsNullOrWhiteSpace($apiKey) -or [string]::IsNullOrWhiteSpace($projectId)) {
    Write-Host "`n❌ Error: apiKey and projectId are required to activate Firebase Google Sign-In." -ForegroundColor Red
    exit 1
}

$envPath = Join-Path $PSScriptRoot "..\web\.env.local"
$envContent = @"
# Firebase Production Credentials - Generated by Setup Wizard
NEXT_PUBLIC_FIREBASE_API_KEY=$apiKey
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$authDomain
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$projectId
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$storageBucket
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$messagingSenderId
NEXT_PUBLIC_FIREBASE_APP_ID=$appId
"@

Set-Content -Path $envPath -Value $envContent
Write-Host "`n✅ Successfully saved credentials to web\.env.local!" -ForegroundColor Green

Write-Host "`nRebuilding TaskPulse web application with new Firebase configuration..." -ForegroundColor Cyan
npm --prefix (Join-Path $PSScriptRoot "..\web") run build

Write-Host "`n==========================================================" -ForegroundColor Green
Write-Host "✅ Firebase & Google Sign-In is now configured!" -ForegroundColor Green
Write-Host "Open http://localhost:3000 and click 'Sign in with Google' to log in!" -ForegroundColor Green
Write-Host "==========================================================" -ForegroundColor Green
